import { IWhiteboardNode, IWhiteboardEdge } from "@/models/whiteboard";

export interface WhiteboardTemplate {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  category: string;
  iconColor: string;
  nodes: IWhiteboardNode[];
  edges: IWhiteboardEdge[];
}

export const ORG_CHART_NODES: IWhiteboardNode[] = [
  // Glowing Circular Company Logo
  {
    id: "node-logo",
    type: "logo",
    x: 620,
    y: 80,
    width: 140,
    height: 140,
    title: "Company Logo",
    subtitle: "COMPANY NAME\nOrganizational Chart",
    body: "",
    color: "#06B6D4",
    fillType: "tint",
    zIndex: 2,
  },
  // Legend Container
  {
    id: "node-legend",
    type: "legend",
    x: 180,
    y: 110,
    width: 300,
    height: 200,
    title: "LEGEND",
    body: "Insert Company Logo on the space (Optional)\n\nPosition or job function of the team member",
    color: "#FFFFFF",
    fillType: "none",
    zIndex: 1,
  },
  // Pink Sticky Note (Pro-tip from screenshots)
  {
    id: "node-sticky-tip",
    type: "sticky",
    x: 340,
    y: 440,
    width: 200,
    height: 180,
    title: "Pro-tip",
    body: "Pro-tip: create tasks for each member of the org chart. Use that task to add information about the team members that would be helpful to know.",
    color: "#EC4899",
    fillType: "tint",
    zIndex: 2,
  },
  // President (Top executive node)
  {
    id: "node-president",
    type: "task",
    x: 600,
    y: 350,
    width: 200,
    height: 120,
    title: "Add a task here to represent this team member!",
    subtitle: "President",
    color: "#0078D4",
    fillType: "solid",
    status: "Executive",
    zIndex: 2,
  },
  // Vice President (Mid executive left)
  {
    id: "node-vp",
    type: "task",
    x: 460,
    y: 630,
    width: 200,
    height: 120,
    title: "Add a task here to represent this team member!",
    subtitle: "Vice President",
    color: "#0078D4",
    fillType: "solid",
    status: "Leadership",
    zIndex: 2,
  },
  // Executive Assistant (Mid executive right)
  {
    id: "node-ea",
    type: "task",
    x: 760,
    y: 630,
    width: 200,
    height: 120,
    title: "Add a task here to represent this team member!",
    subtitle: "Executive Assistant",
    color: "#0078D4",
    fillType: "solid",
    status: "Support",
    zIndex: 2,
  },
  // Operations Director (Lower left 1)
  {
    id: "node-ops",
    type: "task",
    x: 320,
    y: 810,
    width: 190,
    height: 110,
    title: "Add a task here to represent this team member!",
    subtitle: "Operations Director",
    color: "#0078D4",
    fillType: "solid",
    zIndex: 2,
  },
  // IT Director (Lower center 2)
  {
    id: "node-it",
    type: "task",
    x: 580,
    y: 810,
    width: 190,
    height: 110,
    title: "Add a task here to represent this team member!",
    subtitle: "IT Director",
    color: "#0078D4",
    fillType: "solid",
    zIndex: 2,
  },
  // Marketing Lead (Lower right 3)
  {
    id: "node-mktg",
    type: "task",
    x: 840,
    y: 810,
    width: 190,
    height: 110,
    title: "Add a task here to represent this team member!",
    subtitle: "Marketing Lead",
    color: "#0078D4",
    fillType: "solid",
    zIndex: 2,
  },
];

export const ORG_CHART_EDGES: IWhiteboardEdge[] = [
  {
    id: "edge-pres-vp",
    from: "node-president",
    to: "node-vp",
    fromAnchor: "bottom",
    toAnchor: "top",
    color: "#60A5FA",
    style: "orthogonal",
  },
  {
    id: "edge-pres-ea",
    from: "node-president",
    to: "node-ea",
    fromAnchor: "bottom",
    toAnchor: "top",
    color: "#60A5FA",
    style: "orthogonal",
  },
  {
    id: "edge-vp-ops",
    from: "node-vp",
    to: "node-ops",
    fromAnchor: "bottom",
    toAnchor: "top",
    color: "#60A5FA",
    style: "orthogonal",
  },
  {
    id: "edge-vp-it",
    from: "node-vp",
    to: "node-it",
    fromAnchor: "bottom",
    toAnchor: "top",
    color: "#60A5FA",
    style: "orthogonal",
  },
  {
    id: "edge-ea-mktg",
    from: "node-ea",
    to: "node-mktg",
    fromAnchor: "bottom",
    toAnchor: "top",
    color: "#60A5FA",
    style: "orthogonal",
  },
];

export const WHITEBOARD_TEMPLATES: WhiteboardTemplate[] = [
  {
    id: "org-chart",
    title: "Organizational Chart",
    subtitle: "Visualize your team structure",
    description: "Hierarchical blueprint displaying reporting lines, team roles, and organizational structure with customizable task nodes.",
    category: "Organization",
    iconColor: "from-purple-600 to-indigo-600",
    nodes: ORG_CHART_NODES,
    edges: ORG_CHART_EDGES,
  },
  {
    id: "action-plan",
    title: "Action Plan",
    subtitle: "Turn goals into actionable steps",
    description: "Multi-phase delivery board linking OKRs, quarterly initiatives, sprint bottlenecks, and cross-functional deliverables.",
    category: "Strategy",
    iconColor: "from-emerald-600 to-teal-600",
    nodes: [
      {
        id: "ap-phase-1",
        type: "shape",
        x: 200,
        y: 200,
        width: 220,
        height: 140,
        title: "Phase 1: Discovery & Audit",
        subtitle: "Week 1 - 2",
        body: "• Stakeholder interviews\n• Architecture review\n• Security baseline",
        color: "#10B981",
        fillType: "tint",
      },
      {
        id: "ap-phase-2",
        type: "shape",
        x: 500,
        y: 200,
        width: 220,
        height: 140,
        title: "Phase 2: Core Engineering",
        subtitle: "Week 3 - 6",
        body: "• Chat space & mention engine\n• S3 isolated buckets\n• Whiteboards canvas",
        color: "#0078D4",
        fillType: "tint",
      },
      {
        id: "ap-phase-3",
        type: "shape",
        x: 800,
        y: 200,
        width: 220,
        height: 140,
        title: "Phase 3: Rollout & Launch",
        subtitle: "Week 7 - 8",
        body: "• Customer onboarding\n• Billing validation\n• Performance metrics",
        color: "#8B5CF6",
        fillType: "tint",
      },
    ],
    edges: [
      { id: "ap-e-1", from: "ap-phase-1", to: "ap-phase-2", color: "#10B981", style: "orthogonal" },
      { id: "ap-e-2", from: "ap-phase-2", to: "ap-phase-3", color: "#0078D4", style: "orthogonal" },
    ],
  },
  {
    id: "customer-journey",
    title: "Customer Journey Map",
    subtitle: "Optimize every customer touchpoint",
    description: "Comprehensive end-to-end user touchpoint flow from first discovery and sign-up through enterprise expansion.",
    category: "Experience",
    iconColor: "from-blue-600 to-cyan-600",
    nodes: [
      {
        id: "cjm-1",
        type: "sticky",
        x: 200,
        y: 250,
        width: 180,
        height: 160,
        title: "1. Discovery",
        body: "Client browses pricing page and evaluates tiered seat costs.",
        color: "#3B82F6",
        fillType: "tint",
      },
      {
        id: "cjm-2",
        type: "sticky",
        x: 440,
        y: 250,
        width: 180,
        height: 160,
        title: "2. Registration",
        body: "Completes dev registration or company signup with 6-char org ID.",
        color: "#F59E0B",
        fillType: "tint",
      },
      {
        id: "cjm-3",
        type: "sticky",
        x: 680,
        y: 250,
        width: 180,
        height: 160,
        title: "3. Collaboration",
        body: "Invites colleagues, uses @mentions in chat, drafts team Whiteboards.",
        color: "#10B981",
        fillType: "tint",
      },
      {
        id: "cjm-4",
        type: "sticky",
        x: 920,
        y: 250,
        width: 180,
        height: 160,
        title: "4. Value Realization",
        body: "Executes blueprints, tracks sales pipeline, downloads tax invoices.",
        color: "#EC4899",
        fillType: "tint",
      },
    ],
    edges: [
      { id: "cjm-e-1", from: "cjm-1", to: "cjm-2", color: "#3B82F6", style: "orthogonal" },
      { id: "cjm-e-2", from: "cjm-2", to: "cjm-3", color: "#F59E0B", style: "orthogonal" },
      { id: "cjm-e-3", from: "cjm-3", to: "cjm-4", color: "#10B981", style: "orthogonal" },
    ],
  },
  // 1. MEETING NOTES FUNCTIONAL AREA
  {
    id: "meeting-notes",
    title: "Meeting Notes Area",
    subtitle: "Agendas, action items & key decisions",
    description: "Structured collaborative area designed for team standups, sprint reviews, and executive strategy sessions.",
    category: "Collaboration",
    iconColor: "from-blue-600 to-indigo-600",
    nodes: [
      {
        id: "mn-header",
        type: "shape",
        shapeType: "rectangle",
        x: 150,
        y: 120,
        width: 780,
        height: 70,
        title: "📅 Sprint 42 Architecture & Planning Sync",
        subtitle: "Host: Satyam Himesh | Attendees: @All-Engineering | Duration: 45m",
        color: "#0078D4",
        fillType: "solid",
        zIndex: 2,
      },
      {
        id: "mn-agenda",
        type: "sticky",
        x: 150,
        y: 220,
        width: 240,
        height: 220,
        title: "Agenda & Objectives",
        body: "1. Review S3 multi-tenant bucket isolation\n2. Demo Chat @mentions & saved persons bar\n3. Test Whiteboards double-click creation\n4. Q4 Launch Deliverables timeline",
        color: "#3B82F6",
        fillType: "tint",
        zIndex: 2,
      },
      {
        id: "mn-decisions",
        type: "sticky",
        x: 420,
        y: 220,
        width: 240,
        height: 220,
        title: "Key Decisions",
        body: "✓ Approved: Dedicated MongoDB database per company code\n✓ Approved: 4 chat delivery scopes (Global, Team, Group, Direct)\n✓ Approved: Double left-click opens canvas quick-picker",
        color: "#10B981",
        fillType: "tint",
        zIndex: 2,
      },
      {
        id: "mn-actions",
        type: "sticky",
        x: 690,
        y: 220,
        width: 240,
        height: 220,
        title: "Action Items",
        body: "• Marcus Chen: Hardening Webhook signature retries (Due Friday)\n• Elena Rostova: S3 document vault policy audit\n• David Kim: Canvas zoom & pan calibration",
        color: "#F59E0B",
        fillType: "tint",
        zIndex: 2,
      },
    ],
    edges: [],
  },
  // 2. NOTES & BRAINSTORM FUNCTIONAL AREA
  {
    id: "notes",
    title: "Notes & Brainstorm Area",
    subtitle: "Capture raw thoughts, stickies & insights",
    description: "Creative brainstorming board with 4-quadrant color-coded sticky notes for ideas, blockers, and quick wins.",
    category: "Ideation",
    iconColor: "from-amber-500 to-yellow-600",
    nodes: [
      {
        id: "nt-header",
        type: "shape",
        shapeType: "rectangle",
        x: 150,
        y: 120,
        width: 780,
        height: 60,
        title: "💡 Brainstorming & Raw Notes Area",
        subtitle: "Drop spontaneous insights, feature ideas, and sprint feedback",
        color: "#F59E0B",
        fillType: "solid",
        zIndex: 2,
      },
      {
        id: "nt-ideas",
        type: "sticky",
        x: 150,
        y: 210,
        width: 240,
        height: 200,
        title: "💡 Innovative Ideas",
        body: "• Auto-summarize meeting transcripts using AI\n• Support rich markdown export from whiteboards\n• Add real-time cursor presence for teammates",
        color: "#F59E0B",
        fillType: "tint",
        zIndex: 2,
      },
      {
        id: "nt-blockers",
        type: "sticky",
        x: 420,
        y: 210,
        width: 240,
        height: 200,
        title: "⚠️ Blockers & Risks",
        body: "• Edge runtime timeout on huge file downloads\n• Razorpay webhook signature replay window\n• Cross-tenant query index isolation verification",
        color: "#EF4444",
        fillType: "tint",
        zIndex: 2,
      },
      {
        id: "nt-wins",
        type: "sticky",
        x: 690,
        y: 210,
        width: 240,
        height: 200,
        title: "🚀 Quick Wins",
        body: "• Double-click anywhere to immediately create stickies\n• Saved persons bar 1-click delivery\n• High-contrast dark dot grid aesthetic",
        color: "#10B981",
        fillType: "tint",
        zIndex: 2,
      },
    ],
    edges: [],
  },
  // 3. SYSTEM DIAGRAM FUNCTIONAL AREA
  {
    id: "diagram",
    title: "System Diagram Area",
    subtitle: "Map architectural flows, entities & processes",
    description: "Flowchart and system architecture diagram modeling client, edge routing, services, and multi-tenant persistence.",
    category: "Engineering",
    iconColor: "from-cyan-600 to-blue-600",
    nodes: [
      {
        id: "diag-client",
        type: "shape",
        shapeType: "rounded",
        x: 120,
        y: 220,
        width: 170,
        height: 100,
        title: "Next.js 16 Web Client",
        subtitle: "SPA & Turbopack",
        body: "Browser frontend with React 19",
        color: "#3B82F6",
        fillType: "solid",
        zIndex: 2,
      },
      {
        id: "diag-edge",
        type: "shape",
        shapeType: "rectangle",
        x: 360,
        y: 220,
        width: 180,
        height: 100,
        title: "Edge Middleware",
        subtitle: "JWT & Multi-Tenant Rewrite",
        body: "Verifies token & rewrites /:orgId",
        color: "#8B5CF6",
        fillType: "solid",
        zIndex: 2,
      },
      {
        id: "diag-service",
        type: "shape",
        shapeType: "diamond",
        x: 610,
        y: 200,
        width: 170,
        height: 140,
        title: "Tenant Router",
        subtitle: "RBAC & Scoping",
        body: "Resolves isolated database",
        color: "#06B6D4",
        fillType: "tint",
        zIndex: 2,
      },
      {
        id: "diag-db",
        type: "shape",
        shapeType: "rounded",
        x: 850,
        y: 150,
        width: 170,
        height: 90,
        title: "MongoDB Tenant DB",
        subtitle: "projectManageDB_[CODE]",
        body: "100% Isolated Collections",
        color: "#10B981",
        fillType: "solid",
        zIndex: 2,
      },
      {
        id: "diag-s3",
        type: "shape",
        shapeType: "rounded",
        x: 850,
        y: 290,
        width: 170,
        height: 90,
        title: "AWS S3 Document Vault",
        subtitle: "Isolated Buckets",
        body: "Secure Presigned Storage",
        color: "#F59E0B",
        fillType: "solid",
        zIndex: 2,
      },
    ],
    edges: [
      { id: "e-diag-1", from: "diag-client", to: "diag-edge", color: "#3B82F6", style: "orthogonal" },
      { id: "e-diag-2", from: "diag-edge", to: "diag-service", color: "#8B5CF6", style: "orthogonal" },
      { id: "e-diag-3", from: "diag-service", to: "diag-db", color: "#10B981", style: "orthogonal" },
      { id: "e-diag-4", from: "diag-service", to: "diag-s3", color: "#F59E0B", style: "orthogonal" },
    ],
  },
  // 4. PROJECT PLANNER FUNCTIONAL AREA
  {
    id: "project-planner",
    title: "Project Planner Area",
    subtitle: "Track milestones, deliverables & phases",
    description: "Milestone-driven project roadmap connecting sprint phases, work packages, deliverables, and release targets.",
    category: "Management",
    iconColor: "from-purple-600 to-pink-600",
    nodes: [
      {
        id: "plan-header",
        type: "shape",
        shapeType: "rectangle",
        x: 120,
        y: 110,
        width: 900,
        height: 60,
        title: "📊 Q4 Enterprise Release Project Planner",
        subtitle: "Target Launch: Nov 15 | Progress: 82% | 4 Delivery Milestones",
        color: "#8B5CF6",
        fillType: "solid",
        zIndex: 2,
      },
      {
        id: "plan-phase-1",
        type: "task",
        x: 120,
        y: 200,
        width: 200,
        height: 140,
        title: "Phase 1: Multi-Tenancy Architecture",
        subtitle: "Completed (100%)",
        body: "• S3 bucket auto-provisioning\n• MongoDB isolated databases\n• Dev bypass authentication",
        color: "#10B981",
        fillType: "solid",
        status: "Done",
        zIndex: 2,
      },
      {
        id: "plan-phase-2",
        type: "task",
        x: 350,
        y: 200,
        width: 200,
        height: 140,
        title: "Phase 2: Corporate Chat Space",
        subtitle: "Active (100%)",
        body: "• @Mention auto-suggestion\n• Saved persons quick picker\n• 4 delivery message scopes",
        color: "#0078D4",
        fillType: "solid",
        status: "Active",
        zIndex: 2,
      },
      {
        id: "plan-phase-3",
        type: "task",
        x: 580,
        y: 200,
        width: 200,
        height: 140,
        title: "Phase 3: Whiteboard Studio",
        subtitle: "In Progress (90%)",
        body: "• Dark dot-grid infinite canvas\n• Double left-click creation popover\n• Preloaded functional blueprints",
        color: "#8B5CF6",
        fillType: "solid",
        status: "In Progress",
        zIndex: 2,
      },
      {
        id: "plan-phase-4",
        type: "task",
        x: 810,
        y: 200,
        width: 200,
        height: 140,
        title: "Phase 4: Billing & Enterprise GA",
        subtitle: "Planned (0%)",
        body: "• Dynamic seat pricing formula\n• Tax invoice confirmation\n• Customer pilot onboarding",
        color: "#F59E0B",
        fillType: "solid",
        status: "Planned",
        zIndex: 2,
      },
    ],
    edges: [
      { id: "e-plan-1", from: "plan-phase-1", to: "plan-phase-2", color: "#10B981", style: "orthogonal" },
      { id: "e-plan-2", from: "plan-phase-2", to: "plan-phase-3", color: "#0078D4", style: "orthogonal" },
      { id: "e-plan-3", from: "plan-phase-3", to: "plan-phase-4", color: "#8B5CF6", style: "orthogonal" },
    ],
  },
];

/**
 * Creates and translates nodes and edges of a functional area for instant insertion at specific coordinates
 */
export function createFunctionalArea(
  areaType: "meeting-notes" | "notes" | "diagram" | "project-planner" | "org-chart",
  originX: number,
  originY: number
): { nodes: IWhiteboardNode[]; edges: IWhiteboardEdge[] } {
  const tmpl = WHITEBOARD_TEMPLATES.find((t) => t.id === areaType);
  if (!tmpl || tmpl.nodes.length === 0) return { nodes: [], edges: [] };

  const idSuffix = `${Date.now()}-${Math.floor(Math.random() * 1000)}`;

  // Find min X and min Y of template nodes to calculate relative offset
  const minX = Math.min(...tmpl.nodes.map((n) => n.x));
  const minY = Math.min(...tmpl.nodes.map((n) => n.y));

  const idMap = new Map<string, string>();

  const newNodes: IWhiteboardNode[] = tmpl.nodes.map((node) => {
    const newId = `${node.id}-${idSuffix}`;
    idMap.set(node.id, newId);
    return {
      ...node,
      id: newId,
      x: originX + (node.x - minX),
      y: originY + (node.y - minY),
    };
  });

  const newEdges: IWhiteboardEdge[] = tmpl.edges.map((edge) => {
    return {
      ...edge,
      id: `${edge.id}-${idSuffix}`,
      from: idMap.get(edge.from) || edge.from,
      to: idMap.get(edge.to) || edge.to,
    };
  });

  return { nodes: newNodes, edges: newEdges };
}

